[package]
name = "anita"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r-api = { workspace = true, optional = true }
r-keys = { workspace = true, optional = true }
r-storage = { workspace = true, optional = true }
r-tracing = { workspace = true }

dotenvy = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
rayon = { workspace = true }
eyre = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal"] }
reqwest = { workspace = true, features = ["cookies", "json"] }
clap = { workspace = true, features = ["derive", "env"] }
dialoguer = "0.11.0"

[build-dependencies]
vergen = { version = "8.3.2", features = ["build", "cargo", "git", "gitcl"] }

[features]
default = ["api", "interact"]
api = ["r-api", "r-keys", "r-storage"]
interact = []
