[package]
name = "anita"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
dotenvy = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
rayon = { workspace = true }
eyre = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal"] }
reqwest = { workspace = true, features = ["cookies", "json"] }

clap = { version = "4", features = ["derive", "env"] }

r-api = { path = "../crates/api" }
r-keys = { path = "../crates/keys" }
r-storage = { path = "../crates/storage" }
r-tracing = { path = "../crates/tracing" }

[build-dependencies]
vergen = { version = "8.3.2", features = ["build", "cargo", "git", "gitcl"] }
